#!/bin/bash

function install() {
  readonly installPath="/usr/local/bin/maid"

  chmod +x "$fileName"
  sudo mv "$fileName" "$installPath"

  printf "%s\n" "Maid installed correctly."
}

function downloadFile() {
  local url="https://api.github.com/repos/gabrielcapilla/maid/releases/latest"
  local downloadUrl
  downloadUrl=$(curl -s "$url" | jq -r ".assets[] | select(.name == \"$fileName\") | .browser_download_url")

  if [ -n "$downloadUrl" ]; then
    curl -L -o "$fileName" "$downloadUrl"
    install
  else
    printf "%s\n" "The file '$fileName' could not be found in the provided URL."
  fi
}

function getLastVersion() {
  read -r -p "Install maid? (y/n): " chooseVersion
  chooseVersion=$(echo "$chooseVersion" | tr '[:upper:]' '[:lower:]')

  case $chooseVersion in
  "y")
    readonly fileName="maid"
    downloadFile
    ;;
  "n" | *) exit 0 ;;
  esac
}

function main() {
  local installDir="/usr/local/bin"
  local file="maid"

  if [ -f "$installDir/$file" ]; then
    read -r -p "Upgrade '$file'? (y/n): " upgradeMaid

    case $upgradeMaid in
    "y")
      readonly fileName="maid"
      downloadFile
      ;;
    "n" | *) exit 0 ;;
    esac
  else
    getLastVersion
  fi
}

main
